"""Initial tables

Revision ID: a2ac237efaba
Revises: 74f283c0a53a
Create Date: 2026-06-11 00:38:43.050580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2ac237efaba'
down_revision: Union[str, Sequence[str], None] = '74f283c0a53a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedagang',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedagang_id'), 'pedagang', ['id'], unique=False)
    op.create_index(op.f('ix_pedagang_username'), 'pedagang', ['username'], unique=True)
    op.create_table('episode',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pedagang_id', sa.Integer(), nullable=False),
    sa.Column('total_reward', sa.Float(), nullable=True),
    sa.Column('total_waktu', sa.Integer(), nullable=True),
    sa.Column('jumlah_langkah', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pedagang_id'], ['pedagang.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episode_id'), 'episode', ['id'], unique=False)
    op.create_index(op.f('ix_episode_pedagang_id'), 'episode', ['pedagang_id'], unique=False)
    op.create_table('lokasi',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pedagang_id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pedagang_id'], ['pedagang.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lokasi_id'), 'lokasi', ['id'], unique=False)
    op.create_index(op.f('ix_lokasi_pedagang_id'), 'lokasi', ['pedagang_id'], unique=False)
    op.create_table('q_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pedagang_id', sa.Integer(), nullable=False),
    sa.Column('state_key', sa.String(length=500), nullable=False),
    sa.Column('action', sa.Integer(), nullable=False),
    sa.Column('q_value', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pedagang_id'], ['pedagang.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_q_table_id'), 'q_table', ['id'], unique=False)
    op.create_index(op.f('ix_q_table_pedagang_id'), 'q_table', ['pedagang_id'], unique=False)
    op.create_index(op.f('ix_q_table_state_key'), 'q_table', ['state_key'], unique=False)
    op.create_table('rute_optimal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pedagang_id', sa.Integer(), nullable=False),
    sa.Column('urutan_lokasi', sa.JSON(), nullable=False),
    sa.Column('total_jarak', sa.Float(), nullable=True),
    sa.Column('total_reward', sa.Float(), nullable=True),
    sa.Column('rekomendasi', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pedagang_id'], ['pedagang.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rute_optimal_id'), 'rute_optimal', ['id'], unique=False)
    op.create_index(op.f('ix_rute_optimal_pedagang_id'), 'rute_optimal', ['pedagang_id'], unique=False)
    op.create_table('sesi_penjualan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pedagang_id', sa.Integer(), nullable=False),
    sa.Column('waktu_mulai', sa.DateTime(), nullable=False),
    sa.Column('waktu_selesai', sa.DateTime(), nullable=True),
    sa.Column('stok_awal', sa.Integer(), nullable=True),
    sa.Column('stok_sisa', sa.Integer(), nullable=True),
    sa.Column('total_pendapatan', sa.Integer(), nullable=True),
    sa.Column('total_transaksi', sa.Integer(), nullable=True),
    sa.Column('total_lokasi_dikunjungi', sa.Integer(), nullable=True),
    sa.Column('durasi_total', sa.Float(), nullable=True),
    sa.Column('kondisi_cuaca', sa.String(length=50), nullable=True),
    sa.Column('hari_kuliah', sa.Integer(), nullable=True),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pedagang_id'], ['pedagang.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sesi_penjualan_id'), 'sesi_penjualan', ['id'], unique=False)
    op.create_index(op.f('ix_sesi_penjualan_pedagang_id'), 'sesi_penjualan', ['pedagang_id'], unique=False)
    op.create_table('kunjungan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pedagang_id', sa.Integer(), nullable=False),
    sa.Column('lokasi_id', sa.Integer(), nullable=False),
    sa.Column('sesi_id', sa.Integer(), nullable=True),
    sa.Column('waktu_mulai', sa.DateTime(), nullable=False),
    sa.Column('waktu_selesai', sa.DateTime(), nullable=True),
    sa.Column('durasi_mangkal', sa.Float(), nullable=True),
    sa.Column('kondisi_cuaca', sa.String(length=50), nullable=True),
    sa.Column('hari_kuliah', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lokasi_id'], ['lokasi.id'], ),
    sa.ForeignKeyConstraint(['pedagang_id'], ['pedagang.id'], ),
    sa.ForeignKeyConstraint(['sesi_id'], ['sesi_penjualan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kunjungan_id'), 'kunjungan', ['id'], unique=False)
    op.create_index(op.f('ix_kunjungan_lokasi_id'), 'kunjungan', ['lokasi_id'], unique=False)
    op.create_index(op.f('ix_kunjungan_pedagang_id'), 'kunjungan', ['pedagang_id'], unique=False)
    op.create_index(op.f('ix_kunjungan_sesi_id'), 'kunjungan', ['sesi_id'], unique=False)
    op.create_table('penjualan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pedagang_id', sa.Integer(), nullable=False),
    sa.Column('lokasi_id', sa.Integer(), nullable=False),
    sa.Column('kunjungan_id', sa.Integer(), nullable=True),
    sa.Column('jumlah_terjual', sa.Integer(), nullable=False),
    sa.Column('waktu_transaksi', sa.DateTime(), nullable=True),
    sa.Column('waktu_kunjungan', sa.DateTime(), nullable=True),
    sa.Column('durasi_mangkal', sa.Float(), nullable=False),
    sa.Column('kondisi_cuaca', sa.String(length=50), nullable=True),
    sa.Column('hari_kuliah', sa.Integer(), nullable=True),
    sa.Column('reward', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['kunjungan_id'], ['kunjungan.id'], ),
    sa.ForeignKeyConstraint(['lokasi_id'], ['lokasi.id'], ),
    sa.ForeignKeyConstraint(['pedagang_id'], ['pedagang.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_penjualan_id'), 'penjualan', ['id'], unique=False)
    op.create_index(op.f('ix_penjualan_kunjungan_id'), 'penjualan', ['kunjungan_id'], unique=False)
    op.create_index(op.f('ix_penjualan_lokasi_id'), 'penjualan', ['lokasi_id'], unique=False)
    op.create_index(op.f('ix_penjualan_pedagang_id'), 'penjualan', ['pedagang_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_penjualan_pedagang_id'), table_name='penjualan')
    op.drop_index(op.f('ix_penjualan_lokasi_id'), table_name='penjualan')
    op.drop_index(op.f('ix_penjualan_kunjungan_id'), table_name='penjualan')
    op.drop_index(op.f('ix_penjualan_id'), table_name='penjualan')
    op.drop_table('penjualan')
    op.drop_index(op.f('ix_kunjungan_sesi_id'), table_name='kunjungan')
    op.drop_index(op.f('ix_kunjungan_pedagang_id'), table_name='kunjungan')
    op.drop_index(op.f('ix_kunjungan_lokasi_id'), table_name='kunjungan')
    op.drop_index(op.f('ix_kunjungan_id'), table_name='kunjungan')
    op.drop_table('kunjungan')
    op.drop_index(op.f('ix_sesi_penjualan_pedagang_id'), table_name='sesi_penjualan')
    op.drop_index(op.f('ix_sesi_penjualan_id'), table_name='sesi_penjualan')
    op.drop_table('sesi_penjualan')
    op.drop_index(op.f('ix_rute_optimal_pedagang_id'), table_name='rute_optimal')
    op.drop_index(op.f('ix_rute_optimal_id'), table_name='rute_optimal')
    op.drop_table('rute_optimal')
    op.drop_index(op.f('ix_q_table_state_key'), table_name='q_table')
    op.drop_index(op.f('ix_q_table_pedagang_id'), table_name='q_table')
    op.drop_index(op.f('ix_q_table_id'), table_name='q_table')
    op.drop_table('q_table')
    op.drop_index(op.f('ix_lokasi_pedagang_id'), table_name='lokasi')
    op.drop_index(op.f('ix_lokasi_id'), table_name='lokasi')
    op.drop_table('lokasi')
    op.drop_index(op.f('ix_episode_pedagang_id'), table_name='episode')
    op.drop_index(op.f('ix_episode_id'), table_name='episode')
    op.drop_table('episode')
    op.drop_index(op.f('ix_pedagang_username'), table_name='pedagang')
    op.drop_index(op.f('ix_pedagang_id'), table_name='pedagang')
    op.drop_table('pedagang')
    # ### end Alembic commands ###
